name: Trigger
on:
  workflow_dispatch:
    inputs:
      name:
        required: true

jobs:
  trigger-external-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger external workflows
        uses: actions/github-script@v5
        env:
          DISPATCHER_APP_ID=${{ secrets.DISPATCHER_APP_ID }}
          DISPATCHER_APP_PRIVATE_KEY=${{ secrets.DISPATCHER_APP_PRIVATE_KEY }}
          DISPATCHER_CLIENT_ID=${{ secrets.DISPATCHER_CLIENT_ID }}
          DISPATCHER_CLIENT_SECRET=${{ secrets.DISPATCHER_CLIENT_SECRET }}
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const { createAppAuth } = require("@octokit/auth-app")
            const appOctokit = new Octokit({
              authStrategy: createAppAuth,
              auth: {
                appId: process.env.DISPATCHER_APP_ID,
                privateKey: process.env.DISPATCHER_APP_PRIVATE_KEY,
              },
            })
            const installations = appOctokit.rest.apps.listInstallations()
            installations.forEach((installation, i) => {
              const installationOctokit = new Octokit({
                authStrategy: createAppAuth,
                auth: {
                  appId: process.env.DISPATCHER_APP_ID,
                  privateKey: process.env.DISPATCHER_APP_PRIVATE_KEY,
                  installationId: installation.id
                }
              })
              const repositories = installationOctokit.rest.apps.listReposAccessibleToInstallation();
              repositories.forEach((repository, j) => {
                installationOctokit.rest.actions.createWorkflowDispatch({
                  owner: repository.owner.login,
                  repo: repository.name,
                  workflow_id: "externally-triggered.yml",
                  ref: 'main',
                  inputs: {
                    name: ${{ github.event.inputs.name }}
                  }
                })
              })
            })