name: Trigger
on:
  workflow_dispatch:
    inputs:
      name:
        required: true

jobs:
  trigger-external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      
      - name: Install node dependencies
        run: |
          npm install @octokit/rest
          npm install @octokit/auth-app

      - name: Trigger external workflows
        uses: actions/github-script@v5
        env:
          DISPATCHER_APP_ID: ${{ secrets.DISPATCHER_APP_ID }}
          DISPATCHER_APP_PRIVATE_KEY: ${{ secrets.DISPATCHER_APP_PRIVATE_KEY }}
          DISPATCHER_CLIENT_ID: ${{ secrets.DISPATCHER_CLIENT_ID }}
          DISPATCHER_CLIENT_SECRET: ${{ secrets.DISPATCHER_CLIENT_SECRET }}
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const { createAppAuth } = require("@octokit/auth-app")

            // Authenticate as the Dispatching GitHub App
            const appOctokit = new Octokit({
              authStrategy: createAppAuth,
              auth: {
                appId: process.env.DISPATCHER_APP_ID,
                privateKey: process.env.DISPATCHER_APP_PRIVATE_KEY,
              },
            })

            // List all installations of the Dispatching GitHub App
            const installationsResponse = await appOctokit.rest.apps.listInstallations()
            const installations = installationsResponse.data
            
            // Iterate through each installation's repositories and dispatch the workflow
            installations.forEach(async (installation, i) => {

              // Authenticate as the installation
              const installationOctokit = new Octokit({
                authStrategy: createAppAuth,
                auth: {
                  appId: process.env.DISPATCHER_APP_ID,
                  privateKey: process.env.DISPATCHER_APP_PRIVATE_KEY,
                  installationId: installation.id
                }
              })

              // List all repositories under the installation
              const repositoriesResponse = await installationOctokit.rest.apps.listReposAccessibleToInstallation()
              const repositories = repositoriesResponse.data.repositories
              
              // Create a workflow_dispatch event for each repository
              repositories.forEach(async (repository, j) => {
                await installationOctokit.rest.actions.createWorkflowDispatch({
                  owner: repository.owner.login,
                  repo: repository.name,
                  workflow_id: "externally-triggered.yml",
                  ref: 'main',
                  inputs: {
                    name: "${{ github.event.inputs.name }}"
                  }
                })
              })
            })